### ISSUE TITLE
'sk' language not working and script reports error

### ISSUE THREAD

**Issue by osintaj** [manucaralmo/GlowCookies#57]
**Describe the bug**
Setting language to 'sk' generates this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'manageCookies')
    at GlowCookies.createDOMElements (glowCookies.min.js:7:663)
    at GlowCookies.render (glowCookies.min.js:7:162)
    at glowCookies.min.js:7:11536
```

And no banner is shown.

**To Reproduce**
Use default config template and change 'en' to 'sk' .

**Expected behavior**
Banner (cookie settings info) should appear in Slovak language.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome / Firefox
 - Version 99 / 98 (for firefox)

**Comment by osintaj** [comment]
Fixed in version 3.1.7 and maybe in earlier version. Thanks
